config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  get '/forrest', to: 'pages#forrest'
  get '/hiive', to: 'pages#hiive'
  get '/fetch', to: 'pages#fetch'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%#= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%#= javascript_include_tag 'https://unpkg.com/scrollreveal@4.0.0/dist/scrollreveal.min.js' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="about-container">
  <div class="about-image-container red-underline">
    <img src="<%= image_path('tristan.jpg') %>" class="about-portrait" alt="Portrait of the full stack ruby on rails developer and creator of tristan.pizza, Tristan Viney">
    <div class="about-text">
      <h2>
        Tristan Viney is passionate about brutally simple, well-crafted ideas and thinks it's silly to write about himself in third person — so enough of that.
      </h2>
    </div>
  </div>

  <div class="about-text-columns about-text">
    <p>
      I'm the former creative director of <a href="http://www.eardrum.com.au" target="blank" class="text-btn-red-sm">Eardrum</a>, won the <a href="http://www.youngglory.com/past-winners" target="blank" class="text-btn-red-sm">Young Glory creativity competition</a>, and have represented Australia 3 times at <a href="https://www.canneslions.com/enter/young-lions-competitions" target="blank" class="text-btn-red-sm">Cannes Young Lions</a>, winning <a href="http://www.campaignbrief.com/2017/09/rosie-stone-and-tristan-viney.html" target="blank" class="text-btn-red-sm">gold in digital</a> & <a href="http://www.campaignbrief.com/2014/06/gpyrs-carl-robertson-and-trist.html" class="text-btn-red-sm">silver in film</a>.
    </p>
    <p>
      View my advertising portfolio <a href="http://tristanviney.com" target="blank" class="text-btn-red-sm">here</a>.
    </p>
    <p>
      My love of problem solving lead me to attend <a href="http://www.lewagon.com" target="blank" class="text-btn-red-sm">Le Wagon</a> Amsterdam (batch #259) to learn how to build my own ideas. I didn't know where it would lead, only it was something I knew I had to do.
      <br>
      After day one, I was hooked.
    </p>
    <p>
      Now, armed with a my <a href="/hire_me.pdf" target="blank" class="text-btn-red-sm">shiny new web developer toolkit</a>, I have a burning desire to continue coding, building ideas, and learning. Currently, I'm learning React & Redux.
    </p>
    <p>
      I'm looking to incorporate my <a href="/resume.pdf" target="blank" class="text-btn-red-sm">7+ years creative problem solving experience</a> into a full stack Ruby on Rails developer position.
    </p>
    <%= link_to "Let's make something together", contact_path, class: 'content-btn-red-sm' %>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="contact-container">
  <div class="contact-info">
    <h1>
      Let's make something together.
    </h1>
    <h2>
      (+31) 684 647 467
    </h2>
    <h2>
      <%= link_to 'hi@tristan.pizza', 'mailto:hi@tristan.pizza', class: 'text-btn-red-lg' %>
    </h2>
    <div class="contact-links">
      <a href="https://github.com/yeniv" target="blank"><i class="fab fa-github-square"></i></a>
      <a href="https://www.linkedin.com/in/tristanviney" target="blank"><i class="fab fa-linkedin"></i></a>
    </div>
  </div>
</div>

app/views/pages/fetch.html.erb
<div class="case-study-header">
  <div class="case-study-header-info">
    <h1>
      Fetch
    </h1>
    <div class="case-study-tech-stack-text">
      <p>
        Ruby | Ruby on Rails | Heroku | Javascript | CSS | HTML | PostgreSQL | Devise | Carrierwave | Cloudinary | Mapbox API | Geocoder
      </p>
    </div>
    <div class="content-btn-container">
      <%= link_to 'SEE PROJECT', 'http://fetch-dogs.herokuapp.com', target: 'blank', class: 'content-btn content-btn-red'  %>
      <%= link_to 'SEE CODE', 'https://github.com/yeniv/fetch', target: 'blank', class: 'content-btn content-btn-red'  %>
    </div>
  </div>
</div>

<div class="case-study-container case-study-container-white">
  <div class="case-study-text-box case-study-left-text red-text red-border white-bg">
    <p>
      At <a href="http://www.lewagon.com" class="text-btn-red" target="blank">Le Wagon</a>, I worked in a team of 4 to build a web app from scratch with the same functionality as <a href="http://www.airbnb.com" class="text-btn-red" target="blank">Airbnb</a>. We concepted, designed, and coded Fetch in a week.
    </p>
  </div>
  <img src="<%= image_path('fetch/fetch_1.jpg') %>" class="case-study-img-lg-sq case-study-img-top red-border" alt="homepage screenshot of the website fetch, which connects dogless dog lovers with dogs that need walking.">
</div>

<div class="case-study-container case-study-container-white">
  <img src="<%= image_path('fetch/fetch_3.jpg') %>" class="case-study-img-lg case-study-img-top red-border" alt="dogs who need walking on the website fetch">
  <div class="case-study-text-box case-study-right-text red-text red-border white-bg">
    <p>
      Fetch connects dogless dog-lovers with dogs who need a walk. Win-win!
    </p>
  </div>
</div>

<div class="case-study-container case-study-container-red white-text">
  <div class="case-study-text-box case-study-left-text red-bg white-text white-border">
    <p>
      Owners add their dog to the website, along with a photo which is uploaded to <a href="https://www.cloudinary.com/" class="text-btn-white" target="blank">Cloudinary</a> with <a href="https://github.com/carrierwaveuploader/carrierwave" class="text-btn-white" target="blank">Carrierwave</a>.
    </p>
  </div>
  <img src="<%= image_path('fetch/fetch_5.jpg') %>" class="case-study-img-lg case-study-img-top white-border" alt="dogs who need walking on the website fetch">
</div>

<div class="case-study-container case-study-container-red white-text">
  <img src="<%= image_path('fetch/fetch_4.jpg') %>" class="case-study-img-md white-border" alt="a dog marker patiently waiting in Leidschendam to be walked.">
  <div class="case-study-text-box case-study-right-text red-bg white-text white-border">
    <p>
      The exact latitude-longitude of the owner's location is calculated using <a href="http://www.rubygeocoder.com/" class="text-btn-white" target="blank">Geocoder</a> and a marker is placed on a <a href="https://www.mapbox.com/" class="text-btn-white" target="blank">Mapbox</a> map in Javascript.
    </p>
  </div>
</div>

<div class="case-study-container case-study-container-white">
  <div class="case-study-text-box case-study-left-text red-text red-border white-bg">
    <p>
      Walkers can search for dogs anywhere in world by using the world map or entering their location, which begins an active record search.
      <br>
    </p>
  </div>
  <img src="<%= image_path('fetch/fetch_6.jpg') %>" class="case-study-img-md red-border" alt="world map with dog markers placed on every contenent. Except Antarctica. No dogs to walk in Antarctica.">
</div>

<div class="case-study-container case-study-container-red white-text">
  <div class="case-study-text-box case-study-left-text red-bg white-text white-border">
    <p>
      When a dog card is clicked, a Javascript event listener  triggers a Mapbox flyto method which moves the map to the dog's location and opens a popup to request a walk.
    </p>
  </div>
  <img src="<%= image_path('fetch/fetch_7.jpg') %>" class="case-study-img-lg white-border" alt="cool beagle dog named big ears who can hear everything waiting to be walked in amsterdam">
</div>

<div class="case-study-container case-study-container-white red-text">
  <img src="<%= image_path('fetch/fetch_9.jpg') %>" class="case-study-img-lg red-border" alt="screenshot from the website Fetch where a user is requesting to walk a bulldog named Bruce.">
  <div class="case-study-text-box case-study-right-text white-bg red-text red-border">
    <p>
      When walkers find a dog they'd like to walk, they make a request by proposing a date, pickup and drop off times, and a personalised message.
    </p>
  </div>
</div>

<div class="case-study-container case-study-container-white red-text">
  <div class="case-study-text-box case-study-left-text white-bg red-text red-border">
    <p>
      Owners and walkers can view all their requests on their profile page and manage their dogs (if any). But only owners have the power to accept or deny requests.
    </p>
  </div>
  <img src="<%= image_path('fetch/fetch_10.jpg') %>" class="case-study-img-lg-sq red-border" alt="screenshot from the website Fetch where a dog owner is reviewing the requests recieved to walk his dog.">
</div>

app/views/pages/forrest.html.erb
<div class="case-study-header">
  <div class="case-study-header-info">
    <a href="https://www.producthunt.com/posts/run-forrest-run?utm_source=badge-top-post-badge&utm_medium=badge&utm_souce=badge-run-forrest-run" target="_blank"><img src="https://api.producthunt.com/widgets/embed-image/v1/top-post-badge.svg?post_id=159143&theme=light&period=daily" alt="Run, Forrest! Run! - Tweet #runforrestrun to make Forrest Gump run another mile. | Product Hunt Embed" style="width: 250px; height: 54px;" width="250px" height="54px" /></a>
    <br><br>
    <h1>
      Run, Forrest! Run!
    </h1>
    <div class="case-study-tech-stack-text">
      <p>
        Ruby | Ruby on Rails | Heroku | Javascript | CSS | HTML | PostgreSQL | Twitter API | Mapbox API | WebSockets | Sidekiq Scheduler | Bootstrap
      </p>
    </div>
    <div class="content-btn-container">
      <%= link_to 'SEE PROJECT', 'http://forrestgump.live', target: 'blank', class: 'content-btn content-btn-red'  %>
      <%= link_to 'SEE CODE', 'https://github.com/yeniv/Run-Forrest-Run', target: 'blank', class: 'content-btn content-btn-red'  %>
    </div>
  </div>
</div>

<div class="case-study-container case-study-container-white">
  <div class="case-study-text-box case-study-left-text red-text red-border white-bg">
    <p>
      In 1979, Forrest Gump started running. 3 years, 2 months, 14 days, 16 hours, and 13,089 miles later he said he was tired... and went home.
    </p>
  </div>
  <img src="<%= image_path('forrest/forrest-run.gif')  %>" class="case-study-img-md red-border" alt="forrest gump running gif as reporter asks 'why are you doing this?'">
</div>

<div class="case-study-container case-study-container-red white-text">
  <img src="<%= image_path('forrest/felt-like-running.gif')  %>" class="case-study-img-md white-border" alt="forrest gump smiling and waving wearing a singlet">
  <div class="case-study-text-box case-study-right-text red-bg white-text white-border">
    <p>
      I wanted to see how long it would take Forrest (and the Internet) to do it again. So I built a Rails app where every time #runforrestrun is Tweeted, Forrest runs one mile across America.
    </p>
  </div>
</div>

<div class="case-study-container case-study-container-white">
  <div class="case-study-text-box case-study-left-text red-text red-border white-bg">
    <p>
      Forrest runs between the 9 known locations from the movie. The GeoJSON route was calculated using the Mapbox Directions API, which generated thousands of latitude-longitude coordinates following the roads.
    </p>
  </div>
  <img src="<%= image_path('forrest/forrest-locations.jpg')  %>" class="case-study-img-lg red-border" alt="forrest gump running gif as reporter asks 'why are you doing this?'">
</div>

<div class="case-study-container case-study-container-red white-text">
  <img src="<%= image_path('forrest/forrest_2.jpg')  %>" class="case-study-img-md white-border" alt="map from forrestgump.live showing forrest gump marker in nebraska">
  <div class="case-study-text-box case-study-right-text red-bg white-text white-border">
    <p>
      However, the API wouldn't calculate a route this long. So I wrote a function combining several API calls and  mapped the coordinates to the, well, map using Javascript.
    </p>
  </div>
</div>

<div class="case-study-container case-study-container-white">
  <div class="case-study-text-box case-study-left-text red-text red-border white-bg">
    <p>
      A scheduled Sidekiq background task calls the <a href="https://developer.twitter.com/en/docs/tweets/search/overview" class="text-btn-red" target="blank">Twitter API</a> every 24-seconds (maximising Twitter's 150 API calls/hour limit) to search for new Tweets using #runforrestrun.
    </p>
  </div>
  <img src="<%= image_path('forrest/forrest_3.jpg')  %>" class="case-study-img-md red-border" alt="tweet from forrestgump.live showing someone using #runforrestrun while playing world of warcraft">
</div>

<div class="case-study-container case-study-container-white">
  <img src="<%= image_path('forrest/forrest_4.jpg')  %>" class="case-study-img-md red-border" alt="forrest gump marker saying i just felt like running in a speech bubble">
  <div class="case-study-text-box case-study-right-text red-text red-border white-bg">
    <p>
      When a new Tweet is found, the Forrest Gump marker moves 1 mile, the map zooms into the new location, and a random Forrest Gump quote appears in a pop-up.
    </p>
  </div>
</div>

<div class="case-study-container case-study-container-red white-text">
  <img src="<%= image_path('forrest/forrest_5.jpg')  %>" class="case-study-img-lg-sq white-border" alt="map from forrestgump.live showing forrest gump marker in nebraska">
  <div class="case-study-text-box case-study-right-text red-bg white-text white-border">
    <p>
      Using WebSockets and Javascript, the new Tweets are dynamically pushed to the top of the DOM and the mile remaining counter is updated.
      <br><br>
      Tweet(s) are stored in a PostgreSQL database and the most recent 50 Tweets are displayed in a custom card. Hash tags, mentions, and links are all clickable.
    </p>
  </div>
</div>

<div id="forrest-final" class="case-study-container case-study-container-red case-study-container-iphone white-text">
  <!-- <div> -->
    <div class="case-study-text-box case-study-center-text red-bg white-text white-border">
      <p>
        The site has been optimised for mobile using the Bootstrap grid. You know, for those on the go!
      </p>
    </div>
    <img src="<%= image_path('forrest/forrest-iphone.png')  %>" class="case-study-img-iphone" alt="map from forrestgump.live showing forrest gump marker in nebraska">
  <!-- </div> -->
</div>

app/views/pages/home.html.erb
<!-- header section -->
<div class="home-container site-container-white">
  <div class="home-header">
    <h1>
      Creative problem solver<span>*</span><br class="headline-break">meets rails full stack<br class="headline-break">
      developer.
    </h1>
    <h3>
      *Award-winning, just sayin'
    </h3>
    <i class="home-arrow fas fa-chevron-down"></i>
  </div>
</div>
<!-- run forrest run section -->
<div id="forrest" class="site-container site-container-red">
  <div class="home-content">
    <img src="<%= image_path('forrest/forrest_hero_wide.jpg') %>" class="home-image-forrest white-border-home" alt="forrest gump running across a map of america">
    <div class="home-description home-description-red white-border-home white-text-home">
      <h2 class='white-underline'>
        Run, Forrest! Ruuuuuuun!
      </h2>
      <p class="product-hunt-padding-top">
        Every time <a class='text-btn-white' href='https://twitter.com/search?q=%23runforrestrun'>#runforrestrun</a> is Tweeted, Forrest Gump runs another mile across America.
      </p>
      <a href="https://www.producthunt.com/posts/run-forrest-run?utm_source=badge-top-post-badge&utm_medium=badge&utm_souce=badge-run-forrest-run" target="_blank"><img src="https://api.producthunt.com/widgets/embed-image/v1/top-post-badge.svg?post_id=159143&theme=light&period=daily" alt="Run, Forrest! Run! - Tweet #runforrestrun to make Forrest Gump run another mile. | Product Hunt Embed" style="width: 250px; height: 54px;" width="250px" height="54px" /></a>
      <div class="content-btn-container product-hunt-padding-bottom">
        <%= link_to 'SEE PROJECT', 'http://forrestgump.live', target: 'blank', class: 'content-btn content-btn-white' %>
        <%= link_to 'CASE STUDY', forrest_path, class: 'content-btn content-btn-white' %>
      </div>
    </div>
  </div>
</div>
<!-- hiive section -->
<div id="hiive" class="site-container site-container-white">
  <div class="home-content">
    <div class="home-description home-description-white red-border-home red-text">
      <h2 class='red-underline'>
        hiive
      </h2>
      <p>
        hiive helps content creators monetise their channel by instantly transforming referral links into online stores.
      </p>
      <div class="content-btn-container">
        <%= link_to 'SEE PROJECT', 'http://hiive.buzz', target: 'blank', class: 'content-btn content-btn-red'  %>
        <%= link_to 'CASE STUDY', hiive_path, class: 'content-btn content-btn-red'  %>
      </div>
    </div>
    <img src="<%= image_path('hiive/hiive_home_page_center.jpg') %>" class="home-image-hiive red-border" alt="hiive.buzz website homepage screnshot">
  </div>
</div>
<!-- fetch section -->
<div id="fetch" class="site-container site-container-red">
  <div class="home-content">
        <img src="<%= image_path('fetch/fetch_home_screen_center.jpg') %>" class="home-image-fetch white-border-home" alt="forrest gump running across a map of america">
    <div class="home-description home-description-red white-border-home white-text-home">
      <h2 class='white-underline'>
        Fetch
      </h2>
      <p>
        No dog? No worries. Find one that needs walking anywhere in the world.
      </p>
      <div class="content-btn-container">
        <%= link_to 'SEE PROJECT', 'http://fetch-dogs.herokuapp.com', target: 'blank', class: 'content-btn content-btn-white'  %>
        <%= link_to 'CASE STUDY', fetch_path, class: 'content-btn content-btn-white'  %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer-container'>

  <div class="footer-content">
    <p>🍕</p>
    <h3>Don't click the pizza</h3>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class='nav-container'>
  <div class='nav-left'>
    <%= link_to 'TRISTAN ', root_path, class: 'nav-title' %>
    <%= link_to '', root_path, class: 'nav-text-update nav-title' %>
  </div>
  <div class='nav-right'>
    <%= link_to 'RESUME', '/hire_me.pdf', target: '_blank', class: 'nav-link' %>
    <%= link_to 'ABOUT', about_path, class: 'nav-link' %>
    <%= link_to 'CONTACT', contact_path, class: 'nav-link-btn' %>
    <i class="fas fa-bars nav-bar-menu"></i>
  </div>
</div>

<!-- hamburger menu for mobile -->

<div class="nav-bar-menu-popup hidden">
  <i class="fas fa-times nav-bar-popup-close"></i>
  <div class="nav-bar-link-container">
    <%= link_to 'PROJECTS', root_path, class: 'nav-bar-link' %>
    <%= link_to 'RESUME', '/hire_me.pdf', target: 'blank', class: 'nav-bar-link' %>
    <%= link_to 'ABOUT', about_path, class: 'nav-bar-link' %>
    <%= link_to 'CONTACT', contact_path, class: 'nav-bar-link' %>
  </div>
</div>